[project]
name = "docker-workshop-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bodnar4yk", email = "43936158+bodnar4yk@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "psycopg2>=2.9.12",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.52",
    "tqdm>=4.70.0",
]

[project.scripts]
docker-workshop-learn = "docker_workshop_learn:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
